### ISSUE TITLE
Login without password

### ISSUE THREAD

**Issue by p3k777** [programmingforliving/sonar-ad-plugin#9]
sonar-ad-plugin-0.5.jar
sonarqube-4.5.2

User are able login to SonarQube without password with all privileges for this user.
In sonar.log warning appear:
2015.08.27 15:11:50 WARN  web[o.p.s.p.a.ContextUtil]  Failed to retrieve the attributes of xxxxxxx. Error: [LDAP: error code 1 - 000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1 ]

**Comment by jijisv** [comment]
Thank you for the report.

The issue has been fixed and released a new version of sonar ad plugin.

**Comment by p3k777** [comment]
Thanks for quick response, could you add new version to Download, please. Thanks

**Comment by p3k777** [comment]
Sorry only change name, new version is already there
